[book]
#  This book is called
title = "Introduction to building an IOT server and IOT devices in Rust"
# ...but friends call it "Iot Server RS"
authors = ["John Murray and Tyler Crawford"]
multilingual = false
language = "en"
src = "src"

[build]
build-dir = "public"
build-command = "mdbook build"

# [output.html]
# # curly-quotes = true
# smart-punctuation = true
# additional-css = ["src/special-content.css"]
# git-repository-url = "https://github.com/jwmurray/iot_rs"
# site-url = "/book/"

# Linkcheck doesn't find images/SVG so it's not enabled for now
# [output.linkcheck]
